name: Pre-merge CentOS Stage4

on:
  push:
    paths:
      - '.github/workflows/pre-merge/test-centos-stage4.yml'
      - '.github/workflows/image-base-stage4.yml'
      - 'containers/guild-ops-base/stage4.containerfile'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build guild-ops-base final image
      run: |
        docker build . --file containers/guild-ops-base/stage4.containerfile --compress --no-cache --tag chaincrucial/guild-ops-base:stage4
