name: Pre-merge CentOS Stage1

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/pre-merge/test-centos-stage1.yml'
      - '.github/workflows/image-base-stage1.yml'
      - 'containers/guild-ops-base/stage1.containerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Installing dependencies and build tools
      run: |
        docker build . --file containers/guild-ops-base/stage1.containerfile --compress --tag chaincrucial/guild-ops-base:stage1