name: Pre-merge CentOS Stage2

on:
  push:
    paths:
      - '.github/workflows/pre-merge/test-centos-stage2.yml'
      - '.github/workflows/image-base-stage2.yml'
      - 'containers/guild-ops-base/stage2.containerfile'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Compiling new node software
      run: |
        docker build . --file containers/guild-ops-base/stage2.containerfile --compress --tag chaincrucial/guild-ops-base:stage2
