name: Pre-merge CentOS Stage3

on:
  push:
    paths:
      - '.github/workflows/pre-merge/test-centos-stage3.yml'
      - '.github/workflows/image-base-stage3.yml'
      - 'containers/guild-ops-base/stage3.containerfile'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Install guild-ops and compile addon tools [ cncli, cardano-hw-cli ] tools
      run: |
        docker build . --file containers/guild-ops-base/stage3.containerfile --compress --tag chaincrucial/guild-ops-base:stage3
