name: Container Image CD cnode Stage

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Compiling new node software suite
      run: |
        docker build . --file containers/guild-ops-cnode/ --compress --tag chaincrucial/guild-ops-cnode:stage
    - name: docker push stage3 and latest
      run: |
        docker push chaincrucial/guild-ops-cnode:stage
        docker tag chaincrucial/guild-ops-cnode:stage chaincrucial/guild-ops-cnode:latest
        docker push chaincrucial/guild-ops-cnode:latest
