name: Image cnode test Stage

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Compiling new node software suite
      run: |
        docker build . --file containers/guild-ops-cnode/test-stage --compress --tag chaincrucial/guild-ops-cnode:test-stage
    - name: docker push stage and latest
      run: |
        docker tag chaincrucial/guild-ops-cnode:test-stage chaincrucial/guild-ops-cnode:test
        docker push chaincrucial/guild-ops-cnode:test
