name: Container Image base Stage2

on:
  push:
    paths:
      - 'containers/guild-ops-base/guild-operators-latest-alpha.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Compiling new node software
      run: |
        docker build . --file containers/guild-ops-base/test-stage2 --compress --tag chaincrucial/guild-ops-base-test:stage2
    - name: docker push stage 2
      run: |
        docker push chaincrucial/guild-ops-base-test:stage2
    - name: docker dispatch stage 3
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-base-test-stage3.yml/dispatches --data '{"ref": "master"}'
