name: Image base test Stage4

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build guild-ops-base final image
      run: |
        docker build . --file containers/guild-ops-base/test-stage4.containerfile --compress --no-cache --tag chaincrucial/guild-ops-base:test-stage4
    - name: docker push stage4 and latest
      run: |
        TIMESTAMP=$(date +%s)
        docker tag chaincrucial/guild-ops-base:test-stage4 chaincrucial/guild-ops-base:"${TIMESTAMP}"
        docker tag chaincrucial/guild-ops-base:test-stage4 chaincrucial/guild-ops-base:test
        docker push chaincrucial/guild-ops-base:test-stage4
        docker push chaincrucial/guild-ops-base:"${TIMESTAMP}"
        docker push chaincrucial/guild-ops-base:test
    - name: docker dispatch cnode stage
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-cnode-test-stage.yml/dispatches --data '{"ref": "master"}'
    - name: docker dispatch cncli stage
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-cncli-test-stage.yml/dispatches --data '{"ref": "master"}'
