name: Image base test Stage1

on:
  workflow_dispatch:
  push:
    paths:
      - 'containers/guild-ops-base/cardano-node-latest-tag.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Installing dependencies and build tools
      run: |
        docker build . --file containers/guild-ops-base/test-stage1.containerfile --compress --tag chaincrucial/guild-ops-base:test-stage1
    - name: container push stage 1
      run: |
        docker push chaincrucial/guild-ops-base:test-stage1
    - name: container trigger dispatch stage 2
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-base-test-stage2.yml/dispatches --data '{"ref": "master"}'
