name: Container Image CD base Stage 4

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build guild-ops-base final image
      run: |
        docker build . --file containers/guild-ops-base/stage4 --compress --tag chaincrucial/guild-ops-base:stage4
    - name: docker push stage4 and latest
      run: |
        docker push chaincrucial/guild-ops-base:stage4
        docker tag chaincrucial/guild-ops-base:stage4 chaincrucial/guild-ops-base:latest
        docker push chaincrucial/guild-ops-base:latest
    - name: docker dispatch cnode stage
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-cnode-stage.yml/dispatches --data '{"ref": "master"}'
    - name: docker dispatch cncli stage
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-cncli-stage.yml/dispatches --data '{"ref": "master"}'