name: Get latest Guild release version
on:
  schedule:
    - cron:  '0 */8 * * *'
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch node release version
        run: |
          curl -sL -H "Content-Type: application/json" https://api.github.com/repos/cardano-community/guild-operators/commits/master | jq --raw-output '.sha' > containers/guild-ops-base/guild-operators-latest.txt
      - name: Assigns release version
        run: |
          COMMIT=$(cat ./containers/guild-ops-base/guild-operators-latest.txt)
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          COMMIT=$(cat ./containers/guild-ops-base/guild-operators-latest.txt)
          git config --global user.name ${{ secrets.REPO_SCOPED_USER }}
          git config --global user.email ${{ secrets.REPO_SCOPED_EMAIL }}
          git commit -am "New guild-operators master commit ${COMMIT}"
          git push
          curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-base-stage3.yml/dispatches --data '{"ref": "master"}'
