name: Get latest Node release version
on:
  schedule:
    - cron:  '0 */16 * * *'
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch node release version
        run: |
          curl -sL https://github.com/input-output-hk/cardano-node/releases/latest | grep "tag" | head -1 | sed -n -e 's/^.*tag\///p' | cut -d "\"" -f 1 > containers/guild-ops-base/cardano-node-latest.txt
      - name: Assigns release version
        run: |
          VERSION=$(cat ./containers/guild-ops-base/cardano-node-latest.txt)
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          VERSION=$(cat ./containers/guild-ops-base/cardano-node-latest.txt)
          git config --global user.name ${{ secrets.REPO_SCOPED_USER }}
          git config --global user.email ${{ secrets.REPO_SCOPED_EMAIL }}
          git commit -am "New cardano-node release version ${VERSION}"
          git push
          curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-base-stage2.yml/dispatches --data '{"ref": "master"}'
