name: Get latest Cardano Node tag
on:
  schedule:
    - cron:  '0 */16 * * *'
  workflow_dispatch:

jobs:
  get-latest-cardano-node-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout input-output-hk/cardano-node
        uses: actions/checkout@v2.4.2
        with:
            fetch-depth: 0
            repository: 'input-output-hk/cardano-node'

      - name: Get Latest Tag of cardano-node
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previoustag

      - name: Checkout the local repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Apply latest tag to file
        run: |
          VERSION=${{ steps.previoustag.outputs.tag }} ; echo ${VERSION} | tee ./containers/guild-ops-base/cardano-node-latest-tag.txt
                  
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
        
      - name: Commit latest tag version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          VERSION=$(cat ./containers/guild-ops-base/cardano-node-latest-tag.txt)
          git config --global user.name ${{ secrets.REPO_SCOPED_USER }}
          git config --global user.email ${{ secrets.REPO_SCOPED_EMAIL }}
          git commit -am "New cardano-node master tag ${VERSION}"
          git push
          curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-base-test-stage2.yml/dispatches --data '{"ref": "main"}'
          
      - name: Post run version check
        if:  steps.git-check.outputs.modified == 'false'
        run: |
          VERSION=$(cat ./containers/guild-ops-base/cardano-node-latest-tag.txt) 
          echo "No update with version: ${VERSION}"
