name: Get latest Cardano Node release
on:
  schedule:
    - cron:  '0 */8 * * *'
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - id: nodeversion
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: input-output-hk/cardano-node
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Update node release version
        run: |
          VERSION=${{ steps.nodeversion.outputs.release }} ; echo ${VERSION} > containers/guild-ops-base/cardano-node-latest.txt
      - name: Assigns release version
        run: |
          VERSION=$(cat ./containers/guild-ops-base/cardano-node-latest.txt)
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          VERSION=$(cat ./containers/guild-ops-base/cardano-node-latest.txt)
          git config --global user.name ${{ secrets.REPO_SCOPED_USER }}
          git config --global user.email ${{ secrets.REPO_SCOPED_EMAIL }}
          git commit -am "New cardano-node master release ${VERSION}"
          git push
          curl -XPOST -u "${{ secrets.REPO_SCOPED_USER }}:${{ secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/chaincrucial/guild-ops-containers/actions/workflows/image-base-stage3.yml/dispatches --data '{"ref": "master"}'
