name: Get latest CNCLI release version
on:
  schedule:
    - cron:  '0 */8 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch cncli release version
        run: |
          curl -sL https://github.com/AndrewWestberg/cncli/releases/latest | grep "tag" | head -1 | sed -n -e 's/^.*tag\///p' | cut -d "\"" -f 1 > containers/guild-ops-base/release-versions/cncli-latest.txt
      - name: Assigns release version
        run: |
          VERSION=$(cat ./containers/guild-ops-base/release-versions/cncli-latest.txt)
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name ${{ secrets.REPO_SCOPED_USER }}
          git config --global user.email ${{ secrets.REPO_SCOPED_EMAIL }}
          git commit -am "New release version ${VERSION}"
          git push
