name: Pre-merge DebianSlim Stage2

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/cnode-helper-scripts/cabal-build-all.sh'
      - 'containers/pre-merge/debianslim-stage2.containerfile'
      - '.github/workflows/premerge-debianslim-stage2.yml'
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Compiling new node software
      run: |
        docker build . --file containers/pre-merge/debianslim-stage2.containerfile --compress --tag chaincrucial/pre-merge:debianslim_stage2
