name: Pre-merge Debian Cabal Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Testing cabal-build-all.sh
      run: |
        docker build . --file containers/pre-merge/debian-cabal.containerfile --compress --tag chaincrucial/pre-merge:debian_cabal
