name: Pre-merge CentOS7 Stage1

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/cnode-helper-scripts/prereqsh.sh'
      - 'containers/pre-merge/centos7-stage1.containerfile'
      - '.github/workflows/premerge-centos7-stage1.yml'
  pull_request:
    branches: [ development ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Installing dependencies and build tools
      run: |
        docker build . --file containers/pre-merge/centos7-stage1.containerfile --compress --tag chaincrucial/pre-merge:centos7_stage1