name: Pre-merge RockyLinux8 Cabal Build Tests

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  test-cabal-build-all-with-system-libsodium:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing cabal-build-all.sh -l
      run: |
        echo "Working from PR Branch: ${{ steps.pr_branch.outputs.branch }}"
        docker build . --file containers/pre-merge/rockylinux8-cabal_-l.containerfile --compress --build-arg BRANCH=${{ steps.pr_branch.outputs.branch }}--tag ghcr.io/chaincrucial/pre-merge:rockylinux8_cabal_-l