name: Pre-merge RockyLinux8 Prerequisites

on:
  workflow_dispatch:
  pull_request:
    paths:
      - scripts/cnode-helper-scripts/prereqs.sh

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  test-prereqs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login ghcr.io
    - name: Testing prereqs.sh
      run: |
        docker build . --file files/tests/pre-merge/rockylinux8_prereqs.sh.containerfile --compress -e BRANCH=${{ GITHUB_REF_NAME }} --tag ghcr.io/TrevorBenson/pre-merge:rockylinux8_prereqs
    - name: Push
      run: |
        docker push ghcr.io/TrevorBenson/pre-merge:rockylinux8_prereqs
  test-prereqs-with-system-libsodium:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Testing prereqs.sh -l
      run: |
        docker build . --file files/tests/pre-merge/rockylinux8_prereqs.sh_-l.containerfile --compress -e BRANCH=${{ GITHUB_REF_NAME }} --tag ghcr.io/TrevorBenson/pre-merge:rockylinux8_prereqs_-l
    - name: Push
      run: |
        docker push ghcr.io/TrevorBenson/pre-merge:rockylinux8_prereqs_-l