name: Pre-merge UBI8 Stage1

on:
  workflow_dispatch:
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Installing dependencies and build tools
      run: |
        docker build . --file containers/pre-merge/ubi8-stage1.containerfile --compress --tag chaincrucial/pre-merge:ubi8_stage1