name: Pre-merge RockyLinux8 Cabal Build Test

on:
  workflow_dispatch:

jobs:
  test-cabal-build-all:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract branch from PR
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF}"
      id: pr_branch
    - uses: actions/checkout@v2
    - name: Testing cabal-build-all.sh
      run: |
        echo "Working from PR Branch: ${{ steps.pr_branch.outputs.branch }}"
        docker build . --file containers/pre-merge/rockylinux8-cabal.containerfile --compress --build-arg "BRANCH=${{ steps.pr_branch.outputs.branch }}" --tag ghcr.io/chaincrucial/pre-merge:rockylinux8_cabal