name: Pre-merge CentOS8 Prerequisites

on:
  workflow_dispatch:
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Testing prereqs.sh
      run: |
        docker build . --file containers/pre-merge/centos8-prereqs.containerfile --compress --tag chaincrucial/pre-merge:centos8_prereqs